### ISSUE TITLE
miedziowe.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#10]
Similiar to https://github.com/easylistpolish/easylistpolish/issues/9 Ads remains / text / placeholders "reklama"

### `http://miedziowe.pl/`

![ss017](https://user-images.githubusercontent.com/43844449/48664010-85789180-ea98-11e8-8dbb-d59497a9e9be.png)

### `http://miedziowe.pl/content/view/89731/55/`

![ss018](https://user-images.githubusercontent.com/43844449/48664015-9e814280-ea98-11e8-9404-4d61290d800c.png)

**Comment by easylistpolish** [comment]
Right sign hided. The rest needs extended filters
