### ISSUE TITLE
bp24 detekt adblock

### ISSUE THREAD

**Issue by AroKol78** [easylistpolish/easylistpolish#1055]
[https://bp24.pl/](https://bp24.pl/)
![bp24](https://user-images.githubusercontent.com/70756447/92392918-5163da00-f11f-11ea-8b00-a8d97ddda854.JPG)

**Comment by adblock-filters** [comment]
Hej, dzięki za zgłoszenie. Niestety listy Easylist nie zajmują się blokowaniem okienek/komunikatów typu "anti-adblock".
