### ISSUE TITLE
Cookie message on radiozet

### ISSUE THREAD

**Issue by KrisGalcz** [easylistpolish/easylistpolish#1056]
Hey,
Some domains has broken cookie message. To reproduce go to [radiozet](https://biznes.radiozet.pl/News/15-sierpnia-2020.-Czy-sklepy-beda-otwarte-To-Swieto-Wojska-Polskiego). There's not cookie message. Then add a filter:
`@@||radiozet.pl/extension/adverts/design/standard/javascript/adverts/Quantcast.js`
and refresh the page. Cookie message should be visible. The same problem appear on few more websites so I would propose to add:
`@@/extension/adverts/design/standard/javascript/adverts/Quantcast.js$script,domain=antyradio.pl|chillizet.pl|meloradio.pl|planeta.pl|radiozet.pl`

**Comment by adblock-filters** [comment]
Thanks for the report! 
Filter added.

**Comment by krystian3w** [comment]
Zepsute czy uważasz, że np. EasyPrivacy nie ma prawa ich ukrywać?

**Comment by easylistpolish** [comment]
Hejo,
Na początek zaznaczę, że nie jestem ekspertem w prawie. Jednak chwilę już siedzę w tej tematyce i napiszę jak ja to wszystko rozumiem.

Pierwszą sprawą jest prawo w Unii Europejskiej dotyczące obowiązku pokazywania użytkownikowi informacji o cookie i ich wykorzystaniu na stronie. My jako lista, która służy do blokowania reklam, nie powinniśmy ich ukrywać. Dlatego też adblockery, które są dostępne w Unii, powinny mieć listę EasyPrivacy domyślnie wyłączoną. Oczywiście użytkownik może ją ze świadomością, że pozbędzie się tych informacjii włączyć. Z innej strony, jestem świadomy, że wiele adblocków, które nie są z terytorium Unii, nie dbają o to, ale to ich sprawa.

Drugą sprawą są decyzje sądów w Europie na temat adblockerów jest to, że tak długo jak służą blockowaniu reklam, a nie treści, są legalne. Od razu zaznaczę, że nie było to w Polsce, jednak nasza lista jest dostarczana także dla użytkowników po za granicami. By uniknąć problemów z legalnością tego typu oprogramowania, każda lista, która może być dodana do programu automatycznie (jest to zależne od języka przeglądarki użytkownika, nie od geolokalizacji), tego typu filtry nie powinny być dodawane do list, które służą blokowaniu reklam.

Trzecią sprawą jest to, że jesteśmy częścią Easylist. "Polityka" Easylist mówi jasno, że tego typu listy mają służyć wyłącznie blokowaniu reklam: https://easylist.to/pages/policy.html

Co do EasyPrivacy to jest to lista, która blokuje śledzenie użytkownika. Skutkiem ubocznym może być oczywiście zniknięcie informacji o cookies. Jednak przyczyną było np. zablokowanie skryptu, który śledził.

Oczywiście są też listy, których głównym celem jest blokowanie wiadomości o cookies. Gdzie jeśli ktoś używa takiej listy, można zgłaszać strony, dla których nie ma filtrów.

Tutaj teoretycznie problem może być po stronie autora listy i użytkownika, który dobrowolnie ją dodał, jeśli znajduje się na terenie EU. Jeżeli autor listy nie mieszka w UE, albo zablokował część strony nie celowo (np. strona się zmieniła i filter zaczą działać na inną jej część albo filter zablokował reklamę i wiadomość cookie jednocześnie, co nie było widoczne, bo już wcześniej zaakceptował cookies, więc wiadomość dla niego tak czy siak nie była widoczna) nie powinien mieć problemu. Co do użytkowników, wątpię, żeby ktoś próbował się procesować z pojedynczymi użytkownikami, za używanie listy do blokowania wiadomości cookies ;)

Mam nadzieję, że rozjaśniłem czemu tego typu zawartość stron nie jest/nie powinna być blokowana na listach, które służą blokowaniu reklam, szczególnie jeśli nazywają się Easylist + nazwa języka. :)

Jeszcze raz zaznaczę, że nie jestem prawnikiem, tak ja rozumiem cały "problem", po wielu rozmowach i czytaniu rzeczy dotyczących tego problemu. ;)

Pozdrawiam
