### ISSUE TITLE
autokult.pl + gadzetomania.pl + money.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#108]
On autokult.pl + gadzetomania.pl due to this filter: 
https://github.com/easylistpolish/easylistpolish/blob/f4757a89d0d270511e827db3aca6ddc9988067bb/easylistpolish/easylistpolish_specific_block.txt#L1921

all videos in articles are missing.

Example article: https://autokult.pl/33761,test-peugeota-508-auto-dla-kierowcy-stworzone-na-dlugie-trasy

<details not-open>
<summary>autokult.pl screenshoots comparision 1</summary>

![autokult_compare](https://user-images.githubusercontent.com/43844449/57582124-2cc30800-74c1-11e9-9bf5-9b9d0694bd1c.png)

</details>

Example article: https://gadzetomania.pl/60179,klawiatura-qwerty-kto-wymyslil-tak-niewygodne-ulozenie-klawiszy

<details not-open>
<summary>gadzetomania.pl screenshoots comparision</summary>

![gadzetomania_compare](https://user-images.githubusercontent.com/43844449/57582188-0487d900-74c2-11e9-9eb0-2faf952e7230.png)

</details>

On money.pl due to this filter: 

https://github.com/easylistpolish/easylistpolish/blob/f4757a89d0d270511e827db3aca6ddc9988067bb/easylistpolish/easylistpolish_specific_block.txt#L1920

Example article: https://www.money.pl/gospodarka/targi-pracy-w-londynie-rzad-zacheca-polakow-do-powrotu-6380185072297601a.html

<details not-open>
<summary>money.pl screenshoots comparision</summary>

![money_compare](https://user-images.githubusercontent.com/43844449/57582337-bc69b600-74c3-11e9-8bd8-eb38472e9817.png)

</details>

**Comment by easylistpolish** [comment]
Thank you for the issue report. Filters was deleted. Next week I will try to find something to replace them

**Comment by kulfoon** [comment]
@easylistpolish

Sorry but in this thread: https://github.com/easylistpolish/easylistpolish/issues/109, it was @krystian3w who abused against @garggul, because the bug was orginally found and reported by garggul at the polish filters repo here : https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-491812884 and then at EasyList repo here:https://github.com/easylist/easylist/issues/3439, and there was no problem that krystian3w reported (copy & pasted) the bug here at EasyList Polish repo but the problem was that he didn't even mentioned garggul as the original author nor he linked to garggul's thread / comment as the original source, which all the rude behaviour of krystain3w is known as a plagiarism, and was what offended garggul, so garggul just said a word to krystian3w to not do that. And you just made it vice-versa and choose garggul as the offender, not mentioning the fact that the your wrong punishment against garggul could have ended on removing the comment, yet you abused your privileges and were very rude to ban/block garggul from the whole repository just because garggul didn't want his work to be plagairised by krystian3w, also by removing garggul's whole comment (you could hide the single "clown" word) you removed evidence on what krystian3w did and what garggul said. As seen not garggul was the one who first abused the other, but the others (@krystian3w and @easylistpolish) are the ones who abused garggul.

Because of ther above presented rude behavour and abuse against garggul by @easylistpolish I won't contribute to this repository anymore, I hope you won't threat me now the same rude and abusive way you threated garggul, and you won't remove my comment nor ban me, because there is no reason to do that and I'm just talking calmly. Bye.
