### ISSUE TITLE
diety.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#109]
```
https://diety.wp.pl/artykul10821_Dieta-selfie-serio.html
```

Cut no ad foto on page. [](https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-491812884)

![](https://user-images.githubusercontent.com/50133507/57622845-bf7da880-758e-11e9-8da7-d39a3a818a57.png) | ![](https://user-images.githubusercontent.com/50133507/57623242-aa554980-758f-11e9-89f4-be90e49f453c.png)
--- | ---
Gone | should comeback.

---

Broken by `/reklama/*` - <sup>https://github.com/easylist/easylist/blob/8351bc33b18b08ab4ef6da806c9f7877b66ccccd/easylist/easylist_general_block.txt#L6080</sup>

---

# possible fix:

```
@@||filesrr.vitalia.pl/gfx/tstmp20150102023212/reklama/danie.png$image,third-party,domain=diety.wp.pl
```
or

```
@@||filesrr.vitalia.pl/gfx/tstmp*/reklama/*$image,third-party,domain=diety.wp.pl
```

**Comment by garggul** [comment]
Pajacu, jeśli tak bardzo chcesz duplikować cudze zgłoszenie (żeby tamten nie przegapił) to ok, ale link do mojego oryginału https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-491812884 na początku komentarza proszę, normalnie złodziejstwo w biały dzień...

**Comment by easylistpolish** [comment]
No abusing other users here. Comment was deleted. User baned

**Comment by easylistpolish** [comment]
Thank you for the issue. Filter was added:

`@@||filesrr.vitalia.pl^*^reklama/danie.$image,third-party,domain=wp.pl`
