### ISSUE TITLE
fizjoterapeutom.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#11]
As per 
https://github.com/MajkiIT/polish-ads-filter/issues/9010 and 
https://github.com/MajkiIT/polish-ads-filter/issues/9117
Ads remains / text / placeholders "reklama"

**Comment by easylistpolish** [comment]
IMO it's not so distracting. After adding filters all content is moving to the left instead of spreading out and there is a possibility they will put on left or right column some content in future. (the only way to block it in simple way is to block whole column

**Comment by kulfoon** [comment]
> easylistpolish : After adding filters all content is moving to the left instead of spreading out 

You didn't tell what filters are you talking about, perhaps your filters do cause such issue, but after addnig my filter, there is no such issue: 
https://github.com/kulfoon/polish-ads-filter/commit/f70cd7cc3faf2c7d1aaa54815f7a536ac3cd15c4#diff-711027ed0794992ae3b8710d874f3df7R911

**Comment by easylistpolish** [comment]
Yep, still it doesn't spread out content.

**Comment by kulfoon** [comment]
It's not about spread the content, I've been asking if it still is moving to the left?
