### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#110]
`https://portal.abczdrowie.pl/`

mam znaleziony błędny filtr z zgłoszenia: https://github.com/MajkiIT/polish-ads-filter/issues/13623

https://github.com/easylistpolish/easylistpolish/blob/5aad5134c372bcd9b8ff5b8e3f02a4dda806b8e6/easylistpolish/easylistpolish_specific_hide.txt#L1551

```
portal.abczdrowie.pl##div[style$="display: block;"]>*:not(.modal__body)
```

to on wycina nawigacje spod przycisku więcej, więc pewnie trzeba pogłówkować nad nowym.

**Comment by krystian3w** [comment]
y

**Comment by easylistpolish** [comment]
Dzięki wielkie za raport! 2 filtry były tego powodem, dodałem do nich parę `:not()` i teraz wyglądają tak:
`#?#div:-abp-properties(min-height:):not([class^="sc-"]):not(.grid__img__container):not(.more-menu__element):not([class^="footer-"])`
`##div[style$="display: block;"]>*:not(.modal__body):not(.content):not(.submenu)`

**Comment by krystian3w** [comment]
A no tak AdGuard może niekoniecznie (niby mają `properties` w opisie jak tworzyć filtry) z uBO (uBO ingnoruje jako błędny filtr) umieją zinterpretować `abp-properties`.
