### ISSUE TITLE
slideplayer.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#111]
Jakaś literówka od roku:

```
||slideplayer.pl/sli$f~third-party,image
```

https://github.com/easylistpolish/easylistpolish/blob/8ab7ee98e3341c4b1b05f573fed4715bb6379b95/easylistpolish/easylistpolish_specific_block.txt#L1482

`slif`?

**Comment by easylistpolish** [comment]
Dzięki wielkie!:) Naprawione:
||slideplayer.pl/sli$~third-party,image
