### ISSUE TITLE
filme.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#112]
Banner graficzny do filmu Kler: 

`https://filme.pl/filmy-online/Kraina_Lodu__Przygoda_Olafa/2588`

> ![obraz](https://user-images.githubusercontent.com/35370833/59637065-43f6b480-9155-11e9-9bc1-e9aa9988e773.png) |
> --- |

Filtr wzorowany na Angielskim EasyList:

```
_750_200_
```

Nie wiem czy może to nie powinno trafić do głównego EasyList:

https://github.com/easylist/easylist/blob/master/easylist/easylist_general_block_dimensions.txt#L428

\- ten filtr blokuje reklamę chili w prawej kolumnie już.

---

Nie wiem też czy EasyList wycina reklamy na stronach z materiałami nielegalnymi (bo takie w sumie filmy te są).

**Comment by easylistpolish** [comment]
Zamiast `_750_200_` dodałem filme.pl `^banners^` . Staram się nie dodawać "generic" "dimensions" filtrów do EL polish.
