### ISSUE TITLE
tv.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#113]
resztki po reklamach:

`tv.wp.pl##div[class][height="200"]:not([id])`

ale pewnie za raz zmienią szerokość na fejkową i nadpiszą css-em pewnie.

**Comment by easylistpolish** [comment]
U mnie nie widać różnicy po dodaniu tego filtru. Być może już coś zmienili.

**Comment by krystian3w** [comment]
Mnie dalej blokuje 1 resztkę na mobilu i 6 na pc.

Może to cuda z Anti-CV ale te resztki wyglądają na sztywne (są po zablokowaniu JS).

**Comment by krystian3w** [comment]
Chyba że rezygnujemy, bo WP stwierdza pop-upem że źle działa z "Adblockiem".
