### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by zaba-monika** [easylistpolish/easylistpolish#1176]
https://github.com/MajkiIT/polish-ads-filter/issues/17369
https://github.com/AdguardTeam/AdguardFilters/issues/65741

**Comment by adblock-filters** [comment]
Hej, dzięki za zgłoszenie. Tym razem może spróbujemy rozwiązać problem jakimś filtrem typu snippet - zwykłe filtry nie działają niestety zbyt długo.

**Comment by bug-rules** [comment]
Dwie z lewej są na sztywno osadzone:

![obraz](https://user-images.githubusercontent.com/66819865/96371249-0f3ba880-1161-11eb-9d15-426a83873083.png) |
--- |

Skryptowe rozwiązanie może sprawić, że znikną 3 i 2 będą wisieć.

**Comment by zaba-monika** [comment]
Życzę wam powodzenia, dobrze  byłoby w końcu usadzić te reklamy na dłużej za pomocą skryptu, bo inaczej dalej co tydzień będzie nowe zgłoszenie `elektroda.pl`.

**Comment by bug-rules** [comment]
Pewnie też będzie padać raz na tydzień jak administrator umie szybko przebudować JS.

**Comment by zaba-monika** [comment]
Filtry AdGuard : https://github.com/AdguardTeam/AdguardFilters/commit/1ce8b81b44d670236abfb03c2a88e953da808a17 podziałały 1 dzień i znowu reklamy :smiley:
