### ISSUE TITLE
inwestinfo.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#12]
As per https://github.com/MajkiIT/polish-ads-filter/issues/9122
Ads remains / text / placeholders "reklama"

### `https://www.inwestinfo.pl/`

![ss019](https://user-images.githubusercontent.com/43844449/48664081-86f68980-ea99-11e8-87e5-20f50ccf09bd.png)

### `https://www.inwestinfo.pl/rekomendacje-i-prognozy/rekomendacje/rekomendacja-dm-mbank-kghm-22553.htm`

![ss020](https://user-images.githubusercontent.com/43844449/48664089-bc9b7280-ea99-11e8-9e69-bbfcaca07b91.png)

**Comment by easylistpolish** [comment]
Blocked
