### ISSUE TITLE
nerwica.com

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#124]
Błąd - logowanie nie działa, po kliknięciu "Zaloguj się" nie rozwija się do końca okienko logowania:

![Screenshot_2019-08-05 Nerwica com](https://user-images.githubusercontent.com/43844449/62453428-98d8a380-b772-11e9-9d95-cfc3876e375c.png)

Po wyłączeniu EasyList Polish albo dodaniu:
`nerwica.com#@#div[style$="display: block;"]>*:not(.modal__body):not(.content):not(.submenu)`
rozwija się:

![Screenshot_2019-08-05 Nerwica com2](https://user-images.githubusercontent.com/43844449/62453468-ad1ca080-b772-11e9-9abc-03207cf1e6b2.png)
</details>

**Comment by easylistpolish** [comment]
Problematyczny filtr zostal usuniety
