### ISSUE TITLE
Nadgorliwe działanie filtrów dla nowej wersji pudelek.pl

### ISSUE THREAD

**Issue by pawelruta** [easylistpolish/easylistpolish#126]
W nowej wersji pudelka (dostęp przez https://www.pudelek.pl/setcookie?testab=bbb) reguła:

abczdrowie.pl,autokult.pl,echirurgia.pl,fotoblogia.pl,kafeteria.pl,kardiolo.pl,komorkomania.pl,luxlux.pl,medycyna24.pl,nerwica.com,open.fm,pinger.pl,pogodnie.pl,pudelek.pl,pudelek.tv,pudelekx.pl,pytamy.pl,samosia.pl,smog.pl,snobka.pl,wp.pl#?#div:-abp-properties(min-height:):not([class^="sc-"]):not(.grid__img__container):not(.more-menu__element):not([class^="footer-"]):not([class*="coverage"]):not(.streamshort__photo)

Wycina nie tyko reklamy, ale także treść serwisu. Będziemy wdzięczni za poprawkę

**Comment by easylistpolish** [comment]
Dziękuje bardzo za raport. Problematyczny filtr został usunięty. W przeciągu 15 minut filtry powinny się zaktualizować automatycznie na serwerze, a w ciągu 24h na wszystkich lokalnych maszynach:)
Pozdrawiam
