### ISSUE TITLE
wybory.pless.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#13]
As per https://github.com/MajkiIT/polish-ads-filter/issues/9139
Ad remain / text / placeholder "reklama"

**Comment by easylistpolish** [comment]
Gray space hided, sign left (extended filter need)

**Comment by kulfoon** [comment]
And why not just `wybory.pless.pl##.sidebar > .small.pasek-gray` ?

**Comment by easylistpolish** [comment]
This kind of filters (.class1.class2) are also not best for performance so no worth to add just to hide reklama sign. No I don't have a proof.

**Comment by kulfoon** [comment]
Can you tell it to him? I would like to see the confrontation of you vs him, to find out who is right.
