### ISSUE TITLE
twojecentrum.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#15]
As per https://github.com/MajkiIT/polish-ads-filter/issues/9131
Ad remain / text / placeholder "reklama"

**Comment by easylistpolish** [comment]
Sign left (extended filter needed)

**Comment by kulfoon** [comment]
Not really, it's fixed in POL: polskie filtry do Adblocka i uBlocka anyway, any by the way, as seen, the owner was of a different opinion than you, he didn't need extended filters, he added just: 
`twojecentrum.pl##font > small`.

**Comment by easylistpolish** [comment]
Too generic IMO

**Comment by kulfoon** [comment]
Can you tell it to him? I would like to see the confrontation of you vs him, to find out who is right.
