### ISSUE TITLE
livemecz.com

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#17]
As per https://github.com/MajkiIT/polish-ads-filter/issues/9127
Ad remain / text / placeholder "reklama"

**Comment by kulfoon** [comment]
Still "reklama" `livemecz.com##.adv`:

![ss031](https://user-images.githubusercontent.com/43844449/48696081-2eca9f00-ebe1-11e8-8c35-10133c8ee72b.png)

**Comment by hawkeye116477** [comment]
It's just information about advert place to sell.

**Comment by kulfoon** [comment]
Sure, I know already, since easylistpolish told me that 5 days ago https://github.com/easylistpolish/easylistpolish/issues/20#issuecomment-440320412, but still I would like this useless annoying and disturbing thing to be removed, but unfortunatelly EasyList Polish just like POL: polskie filtry do Adblocka i uBlocka don't remove it.
