### ISSUE TITLE
Adblock2privoxy

### ISSUE THREAD

**Issue by KonoromiHimaries** [easylistpolish/easylistpolish#2]
https://github.com/MajkiIT/polish-ads-filter/issues/8060#issuecomment-397674489

https://github.com/easylistpolish/easylistpolish/blob/master/easylistpolish/easylistpolish_specific_hide.txt#L1267

**Comment by krystian3w** [comment]
fail form easylistpolish side rule; should no have `/` in domain name.

**Comment by wmyrda** [comment]
Rule `liga-ursus.siatkowka.org/###widget_sp_image-2` should not have trailing `/` after host name

**Comment by easylistpolish** [comment]
Thanks a lot for all issues.:) They are corrected
