### ISSUE TITLE
kocham.wielun.pl - Regułki blokujące całą treść strony - gratuluję.

### ISSUE THREAD

**Issue by kitor** [easylistpolish/easylistpolish#2021]
W commicie bb51d803fa56bf2d321aca5c632a5f5eefdce6d0 ktoś tak bardzo chciał się pozbyć statycznego obrazka pod artykułem na [kocham.wielun.pl](kocham.wielun.pl) że zablokował `.module-article`, efektywnie ukrywając całe treści artykułu na stronie. Wyjątkowo udana reguła, szczególnie w wypadku dziennika i obecnej sytuacji politycznej.

Zanim znalazłem to repozytorium zdążyłem odbić się od supportu easylisty jak i od "konieczności weryfikacji" na forum, a co za tym idzie - musiałem przerabiać wszystkie templatki i CSS aby to ominąć. Zmieniła się tylko to że klasa to teraz `.module-article2` - więc możecie łatwo zweryfikować jak cud reguła działała.

Tym samym możecie skasować wszystkie regułki dotyczące tej domeny - i tak już `module-abc` i `module-mrowka` są nieaktualne, więc po co tracić transfer użytkowników.

**Comment by TrollZbozowy** [comment]
Dzień dobry, dziękuje za zgłoszenie, filtry dla kocham.wielun.pl zostały usunięte.
