### ISSUE TITLE
m.gazeta.pl empty space at top

### ISSUE THREAD

**Issue by monzta** [easylistpolish/easylistpolish#2273]
### List the website(s) where you encounter issues with ABP filters 

* `https://m.gazeta.pl/0,0.html`

### Define the problem 

Empty space at the top of the page.

### Screenshot(s) 

![gaz](https://user-images.githubusercontent.com/8057368/135884914-78457f7c-4fdc-4f86-b91c-5fb6ea7c67f4.png)

### List all of your filter lists 

* EasyList
* EasyList Polish

### Tell us about your system configuration 

* Win 10
* Chrome 94
* mobile emulation mode

### Other details 

`gazeta.pl##.DFP-premiumBoardReservedPlace`

**Comment by TrollZbozowy** [comment]
thx, fixed
