### ISSUE TITLE
[NSFW] nagieamatorki.net

### ISSUE THREAD

**Issue by AroKol78** [easylistpolish/easylistpolish#2288]
### List the website(s) where you encounter issues with ABP filters 

* "NSFW" `https://nagieamatorki.net/` 

### Define the problem 
reklama na podstronach
(z boku,na dole oraz na filmach w czasie pauzy)
### Screenshot(s) 
przykładowa reklama: [screenshot](https://user-images.githubusercontent.com/70756447/138674664-35099057-649c-4a8d-852d-4ccea2b8ec0e.PNG) `https://nagieamatorki.net/cipka-po-40-demonstrowana-przez-polke/`

### List all of your filter lists 

uBlock filters
uBlock filters - Legacy
uBlock filters - Badware risks
uBlock filters - Privacy
uBlock filters - Resource abuse
uBlock filters - Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
uBlock filters - Annoyances
Peter Lowe’s Ad and tracking server list
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
EasyList Polish
KAD - Przekręty
NoCoin Filter List

### Tell us about your system configuration 

- Operating system and version: win
- Browser and version: Serpent52 + uBlock-legacy

### Other details 
moja propozycja (czasem coś przepuści i nie działa w filmach)
`||appboxes.co/wp-content/uploads/nagam/$domain=nagieamatorki.net`

**Comment by adblock-filters** [comment]
Dzięki bardzo za zgłoszenie!
Dodaliśmy filtr do tej strony.
