### ISSUE TITLE
money.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#24]
![obraz](https://user-images.githubusercontent.com/35370833/49333792-4a607d00-f5c5-11e8-9664-2b201fa022f6.png) |
--- |

Ad remnant above navigation / header.

```
www.money.pl###app > div[data-reactroot] > div[class^="sc-"] + div[class*=" "]:not([class^="sc-"]):nth-of-type(6)
```

**Comment by kulfoon** [comment]
> krystian3w :
> 
> ```
> www.money.pl###app > div[data-reactroot] > div[class^="sc-"] + div[class*=" "]:not([class^="sc-"]):nth-of-type(6)
> ```

You must be kidding if you think that the admin is gonna add such filter, better forget about it: 
https://github.com/easylistpolish/easylistpolish/issues/13#issuecomment-441596819, https://github.com/easylistpolish/easylistpolish/issues/18#issuecomment-441596775, https://github.com/easylistpolish/easylistpolish/issues/19#issuecomment-441594470

**Comment by easylistpolish** [comment]
Hey,
I found a way to hide most of empty spaces by blocking filter. For top space I added "1 day filter". Filter used: ||std.wpcdn.pl/wpjslib/wpjslib-sgap.js|$domain=money.pl|autokult.pl

**Comment by krystian3w** [comment]
And possible broke Gemius...

**Comment by easylistpolish** [comment]
Yep, that's right but if it contains ads inside and blocking it is not breaking the page I thing is worth to push filter. Anyway I found another way to block it
||money.wp.pl^$script,third-party
