### ISSUE TITLE
limanowa.in

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#25]
Ad remain / text "reklama" + it's container:

1
![ss368](https://user-images.githubusercontent.com/43844449/50154292-41f88980-02c9-11e9-9327-32ea7e629a86.png)

1 (wider view)
![ss369](https://user-images.githubusercontent.com/43844449/50154369-7704dc00-02c9-11e9-95c4-eb34724e1b2b.png)

**Comment by easylistpolish** [comment]
Can't reproduce. I don't see it.

**Comment by kulfoon** [comment]
Right, seems that other filter lists trigger it: https://github.com/olegwukr/polish-privacy-filters/issues/29, so feel free to close it if you want to.
