### ISSUE TITLE
https://m.joemonster.org/

### ISSUE THREAD

**Issue by felippesantos46** [easylistpolish/easylistpolish#2761]
### List the website(s) where you encounter issues with ABP filters 

* https://m.joemonster.org/ 

### Define the problem 
cześć, found some Placeholders - **Mobile**

### Screenshot(s) 
<img width="873" alt="Screenshot 2022-03-31 at 10 30 04" src="https://user-images.githubusercontent.com/65717387/161012131-037b6873-2279-49e8-a601-7c08ee45b509.png">

`###main_billboard`
`###middleRect`
`###bottomRect`

**Comment by TrollZbozowy** [comment]
gracias!
