### ISSUE TITLE
https://spidersweb.pl/

### ISSUE THREAD

**Issue by felippesantos46** [easylistpolish/easylistpolish#2765]
### List the website(s) where you encounter issues with ABP filters 

* https://spidersweb.pl/

### Define the problem 
Placeholders - `##.app-adBox` Should do the trick 😄 

### Screenshot(s) 
<img width="1217" alt="Screenshot 2022-04-01 at 09 02 24" src="https://user-images.githubusercontent.com/65717387/161212286-8e282556-1aae-40b2-8811-6c45f7558ee2.png">

**Comment by TrollZbozowy** [comment]
gracias!
