### ISSUE TITLE
Ads on Poludniowa Oficyna domains

### ISSUE THREAD

**Issue by edivaniadc** [easylistpolish/easylistpolish#2817]
### List the website(s) where you encounter issues with ABP filters 

gostynska.pl
jarocinska.pl
krotoszynska.pl
magazynona.pl
rawicz24.pl
zpleszewa.pl
zwielkopolski24.pl

<img width="899" alt="domains" src="https://user-images.githubusercontent.com/57706597/170094306-7bfb62c1-4f7d-441b-ab9a-1afede5454ac.png">

### Define the problem 

1 - top and in content slider ads (highlighted in red) - search for `.ads__wrapper`
2 - `Reklama` labels throughout the page  (highlighted in blue) - search for `.addWrapper`

### Screenshot(s) 
Sample URL: https://jarocinska.pl/wiadomosci/majowka-2022-zobacz-co-dzieje-sie-w-jarocinie-i-okolicy/l2hj0uu8ilYNMeaZEwWV?trc_abp=1

<img width="1201" alt="ads" src="https://user-images.githubusercontent.com/57706597/170095112-4acb8d97-99cf-4e8f-859e-1a98fb48dfb7.png">

### List all of your filter lists 
ABP filters
EasyList Polish+EasyList

### Tell us about your system configuration 

- Operating system and version: MacOS Monterey
- Browser and version: Chrome Version 101.0.4951.64

### Suggested rules:
`gostynska.pl,jarocinska.pl,krotoszynska.pl,magazynona.pl,rawicz24.pl,zpleszewa.pl,zwielkopolski24.pl##.ads__wrapper`
`gostynska.pl,jarocinska.pl,krotoszynska.pl,magazynona.pl,rawicz24.pl,zpleszewa.pl,zwielkopolski24.pl##.addWrapper` 

Rule: `/_nuxt/*.js` would block them all but it would also prevent the **WCZYTYWANIE KOMENTARZY** section from loading 
<img width="1031" alt="KOMENTARZY" src="https://user-images.githubusercontent.com/57706597/170094381-129c1ee6-1b54-498d-b14c-3804e77c812d.png">

**Comment by TrollZbozowy** [comment]
thank you

**Comment by edivaniadc** [comment]
> gostynska.pl jarocinska.pl krotoszynska.pl magazynona.pl rawicz24.pl zpleszewa.pl zwielkopolski24.pl

@TrollZbozowy I thank you for fixing it :)
