### ISSUE TITLE
portal-polski.pl

### ISSUE THREAD

**Issue by ClusterByte-x** [easylistpolish/easylistpolish#2819]
Brak wyciętych reklam, np. tutaj: https://portal-polski.pl/uwaga-telefony-i-karty-sim-3g-do-wymiany/13068/
<img width="1558" alt="Zrzut ekranu 2022-05-28 o 02 09 03" src="https://user-images.githubusercontent.com/76107417/170801855-850296f4-e95b-4a99-aee9-4c76253a4ef5.png">

**Comment by TrollZbozowy** [comment]
Dzięki
