### ISSUE TITLE
Ad spaces and ad labels on several sites

### ISSUE THREAD

**Issue by edivaniadc** [easylistpolish/easylistpolish#2821]
### List the website(s) where you encounter issues with ABP filters 
 1 - https://www.auto-motor-i-sport.pl/wydarzenia/Toyota-GR-Supra-z-manualna-skrzynia-juz-w-Polsce,47719,1

2 - https://www.menshealth.pl/dieta/Sos-pomidorowy-przepis,16606,1

3 - https://www.motocykl-online.pl/artykuly/Autocasco-na-motocykl-Czy-warto-ile-to-kosztuje-na-co-uwazac,16665,4

4 - https://www.womenshealth.pl/promocje/Najnowsza-kolekcja-butow-Ipanema,16473,1

### Define the problem 
Ad spaces and ad labels (REKLAMA) throughout the page:

### Screenshot(s) 
**1 - Ad labels (REKLAMA)** 

**Filter suggestion:** 
`auto-motor-i-sport.pl,menshealth.pl,motocykl-online.pl,womenshealth.pl#?#.side-right:-abp-has(p:-abp-contains(REKLAMA))`

<img width="1295" alt="motocykl1" src="https://user-images.githubusercontent.com/57706597/171031783-1a9c0066-42b8-4fb4-86cf-ffadfa1e2242.png">

**2- In-content ad space** 

**Filter suggestion:** 
```
auto-motor-i-sport.pl##.amis-optad
menshealth.pl##.mh-optad
**motocykl-online.pl##.mo-optad**
womenshealth.pl##.wh-optad

```
<img width="1324" alt="motocykl2" src="https://user-images.githubusercontent.com/57706597/171031816-d759ffbd-a88c-4c70-98b4-a33db81ee1f1.png">

**3 - Bottom Ad label (REKLAMA)**

**Filter suggestion:** 
`auto-motor-i-sport.pl,menshealth.pl,motocykl-online.pl,womenshealth.pl##.margin-10-top`

<img width="1286" alt="motocykl3" src="https://user-images.githubusercontent.com/57706597/171031831-2f71ba20-d125-4f22-b80f-e47abb6d82df.png">

### List all of your filter lists 
ABP filters + EasyList Polish+EasyList

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version:

**Comment by TrollZbozowy** [comment]
thank you
