### ISSUE TITLE
ads on kiep.pl

### ISSUE THREAD

**Issue by monzta** [easylistpolish/easylistpolish#2867]
### List the website(s) where you encounter issues with ABP filters 

* https://www.kiep.pl/80882/reakcja-kolegow

### Define the problem 

Ads on top, right and middle of the page

### List all of your filter lists 
EasyList+EasyList Polish

### Tell us about your system configuration 

- Operating system and version: Windows 10
- Browser and version: Chrome 103.0.5060.114, ABP 3.14.1

### Other details 
Filter suggestion: `kiep.pl##a[href^="https://www.kiep.pl/assetcdn/get.php?f="]`

**Comment by adblock-filters** [comment]
filters for kiep.pl added, thanks for help!
