### ISSUE TITLE
https://www.skijumping.pl/

### ISSUE THREAD

**Issue by edivaniadc** [easylistpolish/easylistpolish#2958]
### List the website(s) where you encounter issues with ABP filters 
https://www.skijumping.pl/

### Define the problem 
Would you consider these partner banners as self-promo or ads?

Placed at the upper center, right rail and footer
```
a[href^="https://www.blachotrapez.eu/"]
a[href^="https://online.efortuna.pl/"]
a[href^="https://real-logistics.pl/"]

```

### Screenshot(s) 

<img width="1203" alt="sp1" src="https://user-images.githubusercontent.com/57706597/180235014-f05090dd-6c69-4050-a2aa-9763808af10f.png">
<img width="1159" alt="sp2" src="https://user-images.githubusercontent.com/57706597/180235040-88ba100e-c034-4759-a691-e08f49018ca8.png">

### Filters suggestion
```
skijumping.pl##a[href^="https://www.blachotrapez.eu"][target="_blank"]
skijumping.pl##a[href^="https://online.efortuna.pl/"][target="_blank"]
skijumping.pl##a[href^="https://real-logistics.pl"][target="_blank"]
skijumping.pl#?#.footer-box:-abp-has(h3[class^="wiget-title"]:-abp-contains(SPONSORZY))
```

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version:

**Comment by adblock-filters** [comment]
Hi @edivaniadc , thanks for contribution!
I think we can treat them as ads, because of quite big banners in the middle of the website. I've added your filters suggestion and changed the last one a little beat to leave the hyperlinks. ; )
