### ISSUE TITLE
Hidden content in szbk. pl

### ISSUE THREAD

**Issue by locustAbjector** [easylistpolish/easylistpolish#3131]
### List the website(s) where you encounter issues with ABP filters 

* `szbk.pl`
* example page:
`https://szbk.pl/en/auto/toyota_auris/?onlyActual=on&page=1`

### Define the problem 
An alert message pops up asking to whitelist/allow the site.
No results appear on the page.

### Screenshot(s) 
<details>
<summary>See below</summary>

![no-content-pl-site](https://user-images.githubusercontent.com/114186776/202725229-44b56295-7167-40fd-84d2-8325359193ba.jpg)

![alert-pl-site](https://user-images.githubusercontent.com/114186776/202725281-d69ccb87-21f1-479c-9807-f6343e097a62.jpg)

![after-debug-pl-site](https://user-images.githubusercontent.com/114186776/202725325-9f6510c2-19ad-4b39-b059-1dfc1f328a05.jpg)

</details>

### List all of your filter lists 

* Easylist polish
* EasyPrivacy
* Fanboy's social list
* ABP filters

### Other details 

it seems that various generic Easylist filters are the ones causing the problem, I can list some, but there might be more, like for example:

`##.ad-card`
`##.ad-icon`
`##.ad-row`

#### possible filter suggestion:

This seems to solve the problem, as no alert appears after adding the filter

`@@||szbk.pl^$generichide`

**Comment by adblock-filters** [comment]
Hi,
Thank you for your contribution!
Fixed in: [b590696](https://github.com/easylistpolish/easylistpolish/commit/b5906966e0d7e4295790b288b6169519635d9a7c)
