### ISSUE TITLE
Banners ads

### ISSUE THREAD

**Issue by felippesantos46** [easylistpolish/easylistpolish#3132]
### List the website(s) where you encounter issues with ABP filters 

* https://www.mediaexpert.pl/komputery-i-tablety/laptopy-i-ultrabooki/laptopy
* https://www.euro.com.pl/laptopy-i-netbooki.bhtml

### Define the problem 
Banners are placed in-between products and/or sidebar

### Screenshot(s) 
<img width="1510" alt="Screenshot 2022-11-23 at 09 46 33" src="https://user-images.githubusercontent.com/65717387/203503978-44b20d65-0474-41da-9c54-faa7119beb35.png">

**Comment by adblock-filters** [comment]
Unfortunately such banners are auto-promotion of website owner and we are not allowed to block it there. : /
