### ISSUE TITLE
Non ASCII characters 

### ISSUE THREAD

**Issue by felippesantos46** [easylistpolish/easylistpolish#3133]
### Define the problem 
Filters:
`##.insert—top-offer`
`##.grid-item—wpapiad`

List: easylistpolish_specific_hide.txt

Issue: — Is not ASCII

### Other details 
Is it possible to convert those filters to ASCII rules ? Thank you in advance :)

**Comment by adblock-filters** [comment]
Fixed in https://github.com/easylistpolish/easylistpolish/commit/2d0fac2542ac0d6cbfb29a85c392116a802784e0, thanks for spotting it!

**Comment by krystian3w** [comment]
But these characters can be used in artybut class and id:

<div id="insert—top-offer">one</div>
<div id="grid-item—wpapiad">two</div>

```adb
###user-content-insert—top-offer
###user-content-grid-item—wpapiad
```

**Comment by adblock-filters** [comment]
sure, they can, but for this particular website they haven'y been needed
