### ISSUE TITLE
Wykop.pl

### ISSUE THREAD

**Issue by ClusterByte-x** [easylistpolish/easylistpolish#3136]
Wymaga stworzenia nowych filtrów ukrywających reklamy po przebudowie serwisu. 
@TrollZbozowy @easylistpolish 

<img width="1404" alt="Zrzut ekranu 2023-01-19 o 01 15 54" src="https://user-images.githubusercontent.com/76107417/213325916-eff6918c-f162-452d-b4c6-fb5c28652827.png">

**Comment by adblock-filters** [comment]
Nowe filtry dodadne w f1f29fdae08a1806e31659970768603645c3c90b
Dzięki za zgłoszenie

**Comment by ClusterByte-x** [comment]
@adblock-filters 

Można zweryfikować jeszcze raz poprawność filtrów? Niestety przepuszcza reklamę kantora ora AliExpress.
https://wykop.pl/wpis/87343659/ktos-ma-jakis-sprytny-filterek-do-ublock-origin-do
https://wykop.pl/wpis/87402989/mozna-poprosic-kod-do-ublocka-do-zablokowania-tego

**Comment by adblock-filters** [comment]
Cześć, dzięki za info. Zaraz sprawdzę i dodam nowe filtry.

**Comment by ClusterByte-x** [comment]
Na szybko, póki nie ma nic lepszego: wykop.pl##img[src*="b1df9ed"]

**Comment by ClusterByte-x** [comment]
wykop.pl##*:has(> * > a[target="_blank"] > img)
wykop.pl##[data-label^="ad:"]
wykop.pl##section.pub-slot-wrapper
wykop.pl##section.link-block:has(li.recommend-label)
wykop.pl##section.selected:has(> div.content > section.stream.selected-stream)

Niestety, wykrywa to blokadę adblocka. Na uBO wystarczyłoby to ominąć: 
wykop.pl##+js(nostif, checkador)
wykop.pl##+js(nostif, ensureCompatibility)
