### ISSUE TITLE
Allegro.pl

### ISSUE THREAD

**Issue by Genki-pl** [easylistpolish/easylistpolish#3150]
Zasugerowano mi zgłoszenie tematu tutaj.
Reklamy na karcie produktu w Allegro w kilku miejscach: https://github.com/MajkiIT/polish-ads-filter/issues/21984

**Comment by krystian3w** [comment]
Samo zgłoszenie nie wystarczy, lista wciąż nie jest domyślna dla uBlock Origin.

**Comment by garry-ut99** [comment]
No to niech sobie ją doda, może już dodał.

**Comment by Genki-pl** [comment]
Ale lista jest domyślna w kilku innych adblockach więc nie zaszkodzi dodać.
Ja dodałem ją sobie już ręcznie.

**Comment by adblock-filters** [comment]
Cześć, dzięki za zgłoszenie. Niestety te reklamy to "autopromocja" portalu Allegro, więc listy EL nie mogą ich blokować (co innego gdyby taki baner był widoczny na innej stronie, bądź kliknięcie prowadziłoby do innej zewnętrznej strony). 
Prawdopodobnie będziemy musieli też usunąć część filtrów z allegro, które blokują podobne banery.

**Comment by krystian3w** [comment]
Można uruchomić plik `easylistpolish-selfpromo-annyances.txt` i ludzie będą go ręcznie subskrybować.

**Comment by adblock-filters** [comment]
"Co do uwagi o odblokowaniu to jest ona sprzeczna z zasadami anglosaskiej wersji EL (raz zablokowane self-promo nie zostaje już odblokowane)."

Tak dokładnie, dlatego póki co udaje się je wciąż zostawić, pomimo różnych innych pozgłaszanych issue w tej sprawie

**Comment by garry-ut99** [comment]
Kolejne zgłoszenie : 
- https://github.com/MajkiIT/polish-ads-filter/issues/22067

**Comment by garry-ut99** [comment]
> hawkeye116477 : https://github.com/MajkiIT/polish-ads-filter/issues/22067#issuecomment-1787131983 :  Od tego kiedyś był [AlleBlock](https://github.com/maciejtarmas/AlleBlock).

Znalazłem jakiegoś forka: https://github.com/maciejtarmas/AlleBlock/issues/61 ==> https://github.com/CrusheerPL/AlleBlock ==> `https://raw.githubusercontent.com/CrusheerPL/AlleBlock/master/alleblock.txt`, ostatnie zmiany 4 miesiące temu, nie jest super aktualny, ale napewno świeższy od oryginału, może ktoś zasubskrybuje i potestuje.

**Comment by adblock-filters** [comment]
https://github.com/easylistpolish/easylistpolish/pull/3203
