### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3160]
- https://github.com/MajkiIT/polish-ads-filter/issues/20958, a dokładniej : 
https://github.com/MajkiIT/polish-ads-filter/issues/20958#issuecomment-1100222612 (pusty kontener po reklamie u góry)

**Comment by adblock-filters** [comment]
rozwiązane w 2ee05307a658c0a5a85f408ff30bac60c249b7df
`otodom.pl##div[data-cy="search.listing.promoted"]`
