### ISSUE TITLE
echolubonia.pl (błąd)

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3165]
Błąd -  omyłkowo wycięte linki do artykułów :

### Tak jest z włączoną listą EasyListPolish (zepsute) :
![ss_01](https://github.com/easylistpolish/easylistpolish/assets/72945564/e008644e-8f68-4239-9a30-bd02a15654b9)

### A tak jest z wyłączoną (naprawione) :
![ss_02](https://github.com/easylistpolish/easylistpolish/assets/72945564/51be7033-c3eb-401f-9e18-2a2ed3411d3d)

**Comment by adblock-filters** [comment]
Resolved in https://github.com/easylistpolish/easylistpolish/commit/c76586ecd1e633f2d97e4b59b8e541e6b8907329

Thanks for your contribution!
