### ISSUE TITLE
mgsm.pl

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3166]
- https://github.com/MajkiIT/polish-ads-filter/issues/22139

**Comment by adblock-filters** [comment]
resolved, thanks!

**Comment by garry-ut99** [comment]
@adblock-filters: Unfortunately, not all placeholders on the screenshoot have been fixed, only some.

**Comment by adblock-filters** [comment]
![image](https://github.com/easylistpolish/easylistpolish/assets/52950278/14eaf465-08c1-4d16-8b29-63924918b6a1)
this one is not possible to block without blocking other content

![image](https://github.com/easylistpolish/easylistpolish/assets/52950278/948cdf6b-44f7-4830-bda5-c5194cf8f30d)
and this one is mgsm partner, unfortunetely EL Polish can't block such banners

**Comment by garry-ut99** [comment]
@adblock-filters: Not these, what I meant is the last 3 placeholders at the bottom of the screenshoot: https://github.com/MajkiIT/polish-ads-filter/issues/22139

**Comment by adblock-filters** [comment]
Dzięki, sprawdziliśmy, reklamy są blokowane/ukrywane kiedy użytkownik używa EL + EL Polish + abp-filters-anti-cv
