### ISSUE TITLE
resetoff.pl

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3173]
This issue :
- https://github.com/uBlockOrigin/uAssets/issues/21437 

is going to be fixed in `Official Polish Filters for AdBlock, uBlock Origin & AdGuard` soon

Consider fixing it in `EasyList Polish` as well, by adding 2 filters : 
- `resetoff.pl##[id$="reklamy"]:not(h1):not(h2):not(h3):not(h4):not(h5):not(h6):not(b):not(strong)` 
from https://github.com/MajkiIT/polish-ads-filter/blob/24f7f6fe0684489f6320816b82faeb5a1943cae0/polish-adblock-filters/adblock.txt#L169 or an equivalent (maybe you can find a simpler filter specifically for `resetoff.pl`)
- `resetoff.pl##.background-cloud-reseton` discovered by mapx- in 
https://github.com/uBlockOrigin/uAssets/issues/21437#issuecomment-1858803803

**Comment by adblock-filters** [comment]
added in https://github.com/easylistpolish/easylistpolish/commit/9b4fe473db95a1ef579f24312d1e46dfea6fceaf and https://github.com/easylistpolish/easylistpolish/commit/bf1e63b6c71f72fee3003ac8806f88f94c89c83e
thanks!
