### ISSUE TITLE
geekweek.interia.pl

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3175]
### List the website(s) where you encounter issues with ABP filters 

* `https://geekweek.interia.pl/`

### Define the problem 

Uszkodzenie - poprzesuwane 2 kafelki na głównej, niedawno zgłoszone i naprawione tu : 
https://github.com/MajkiIT/polish-ads-filter/issues/20301#issuecomment-1894155552, a teraz patrzę i na `EasyList Polish` to samo, 
2 lata temu dodane : 

https://github.com/easylistpolish/easylistpolish/commit/8547b2087a5cace0f36eebd4af8fc5b33bf7d811
https://github.com/easylistpolish/easylistpolish/blob/83fd419616395b93e5b175072ae93fbc79614ed2/easylistpolish/easylistpolish_specific_hide.txt#L834

https://github.com/easylistpolish/easylistpolish/commit/cdd00c6282410cf9ac8e6dcc9199b6d8bf34315f
https://github.com/easylistpolish/easylistpolish/blob/83fd419616395b93e5b175072ae93fbc79614ed2/easylistpolish/easylistpolish_specific_hide.txt#L960

### Screenshot(s) 

- 1 [POPSUTE](https://github.com/easylistpolish/easylistpolish/assets/72945564/10bcbe39-bf55-467b-a42a-a83965175348)
- 2 [NAPRAWIONE](https://github.com/easylistpolish/easylistpolish/assets/72945564/69765b6a-27bd-4f65-8bee-dbd67d6f4560)

**Comment by adblock-filters** [comment]
Dzięki za zgłoszenie, usunąłem problematyczne filtry ; )
