### ISSUE TITLE
mgsm.pl

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3177]
Reopen, bo wołałem i pingowałem, ale nie było reakcji :
- https://github.com/easylistpolish/easylistpolish/issues/3166#issuecomment-1849554725

**Comment by adblock-filters** [comment]
Dzięki, sprawdziliśmy, reklamy są blokowane/ukrywane kiedy użytkownik używa EL + EL Polish + abp-filters-anti-cv
