### ISSUE TITLE
Grupa WP

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3178]
Grupa WP: na wielu stronach powiązanych z grupą mnóstwo reklam i pustych kontenerów, niektóre reklamy to wewnętrzne/sponsorowane/partnerzy, i wiem że takich nie blokujecie, ale pełno jest także zwykłych reklam i pustych kontenerów do zablokowania.

Przygodę wystarczy zacząć od głównej siedziby `www.wp.pl` na której są reklamy i puste kontenery i potem można klikać w artykuły przechodząc do innych powiązanych z WP domen, na których również są reklamy i puste kontenery, nie mówię że na wszystkich, ale na wielu, być może na większości.

Na niektóre domeny WP to nawet nie wiem czy wejdziecie z Adblockiem, bo was anty-adblock nie wpuści, a wy ponoć anty-adblocków nie rozbrajacie, więc nie wiem w ogóle jak macie zamiar wtedy usunąć te reklamy i kontenery i czy to w ogóle sens je usuwać skoro i tak nie da się wejść, ale na niektórych stronach WP nie ma anty-adblocka, więc przynajmniej na takich stronach możecie wejść i pousuwać reklamy i puste kontenery.

Wiem też, że strony z Grupy WP należą do tzw. złośliwych reklam nawracających i są naprawiane przede wszystkim za pomocą skryptletów w specjalnej liście https://github.com/abp-filters/abp-filters-anti-cv ==> https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv. Nie wiem czy macie z nimi kontakt, czy nie, i nie wiem czy niezależnie od nich możecie dodawać filtry kosmetyczne, ale z całą pewnością oprócz skryptletów można zaaplikować filtry kosmetyczne gdzie się da, w uBlock Origin właśnie w taki sposób zostały skutecznie wybite reklamy i puste kontenery na wszystkich domenach WP: https://github.com/uBlockOrigin/uAssets/issues/12214

**Comment by adblock-filters** [comment]
Dzięki, sprawdzimy filtry z uBlocka i zobaczymy, czy któreś da się przekazac do kolegów z anti-CV

**Comment by garry-ut99** [comment]
Jak coś to część filtrów kosmetycznych do WP jest w `Polskie Oficjanle Filtry` a część w `uBlock - Ads` , więc należy szukać filtrów do WP w obywu tych listach.
