### ISSUE TITLE
Grupa INTERIA

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3180]
Grupa INTERIA - pełno dużych szarych pustych kontenerów po reklamach na wielu powiązanych domenach/poddomenach (główna strona jest akurat czysta).

Przygodę wystarczy zacząć od głównej siedziby `www.interia.pl` gdzie akurat nie ma pustych kontenerów, ale potem wystarczy klikać w artykuły przechodząc do innych powiązanych z INTERIA domen/poddomen, na których są puste kontenery, nie mówię że na wszystkich, ale na wielu, być może na większości.

Przykładowy zrzut ekranu : 
( `https://wydarzenia.interia.pl/raport-ukraina-rosja/news-rosjanie-zajmuja-awdijiwke-agent-ujawnia-bedziemy-musieli-op,nId,7319321` )

![ss_12](https://github.com/easylistpolish/easylistpolish/assets/72945564/af2b7382-d1d4-4aca-8200-483c66ae572b)

**Comment by adblock-filters** [comment]
Dzięki, zgłoszone do anti-CV, jako że to dynamiczne nazwy klas i idków wykraczają poza możliwości list standardowych.
