### ISSUE TITLE
Grupa ONET (reopen 2)

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3195]
Otwieram ponownie, bo znowu zamknięte i nie porobione :
- https://github.com/easylistpolish/easylistpolish/issues/3192

Zastanawiam się co za cyrki się tu dzieją, oraz wnoszę o nie zamykanie zgłoszeń bez uprzedniego upewnienia się, że są porobione, a w innym przypadku o wyjaśnienie, dlaczego nieporobione zgłoszenia są zamykane.

**Comment by adblock-filters** [comment]
Nie wszystkie zgłoszone banery do reklamy lub obiekty blokowane przez EL Polish. Poprawne filtry są gotowe, czekają na opublikowanie w nowej wersji, proszę nie otwieraj ponownie zgłoszeń.
