### ISSUE TITLE
Grupa MEDIA OPERATOR (reopen)

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3198]
Otwieram ponownie, bo znowu zamknięte i nie porobione :
- https://github.com/easylistpolish/easylistpolish/issues/3186

Zastanawiam się co za cyrki się tu dzieją, oraz wnoszę o nie zamykanie zgłoszeń bez uprzedniego upewnienia się, że są porobione, a w innym przypadku o wyjaśnienie, dlaczego nieporobione zgłoszenia są zamykane.

**Comment by adblock-filters** [comment]
Nie wszystkie zgłoszone banery do reklamy lub obiekty blokowane przez EL Polish. Poprawne filtry są gotowe, czekają na opublikowanie w nowej wersji, proszę nie otwieraj ponownie zgłoszeń.

**Comment by garry-ut99** [comment]
> Nie wszystkie zgłoszone banery do reklamy lub obiekty blokowane przez EL Polish. 

Było dużo reklam/kontenerów po reklamach które powinny być zablokowane a nie były.

> Poprawne filtry są gotowe, czekają na opublikowanie w nowej wersji, 

Testowałem 2 dni po zamknięciu zgłoszeń, wszystkie listy miałem zaktualizowane, to kiedy niby mam testować.

> proszę nie otwieraj ponownie zgłoszeń.

To ich kur... nie zamykaj kiedy dalej pełno reklam i kontenerów jest.
