### ISSUE TITLE
eska.pl (breakage)

### ISSUE THREAD

**Issue by garry-ut99** [easylistpolish/easylistpolish#3205]
### List the website(s) where you encounter issues with ABP filters 

`https://www.eska.pl/`
`https://nerdsfera.eska.pl/`
`https://nerdsfera.eska.pl/rise-of-the-ronin-ze-swoim-odpowiednikiem-na-pc-od-sony-firma-chce-zachecic-graczy-do-kupna-ps5-aa-1YUA-6yWq-st7h.html`

I może jeszcze kilka innych poddomen `*.eska.pl` (wszystkich nie oblatywałem).

### Define the problem 

Popsuta strona/ puste biała.

### Screenshot(s) 

POPSUTE: [SCREENSHOOT 1](https://github.com/user-attachments/assets/19c025d8-2d06-48a9-8ddc-abf63fa2dd2a)
NAPRAWIONE: [SCREENSHOOT  2](https://github.com/user-attachments/assets/44ed2fee-9890-48b4-afe2-09871f744ba0)

</details>

### Tell us about your system configuration 

- Operating system and version: 
- Browser and version: Any

### Other details 

Spowodowane tym: https://github.com/easylistpolish/easylistpolish/commit/23f2c75171da0ea4d458ab550c2f7c38c06a920b :
https://github.com/easylistpolish/easylistpolish/blob/74b9360d41a3053e74cb32bf25a7c7ad105b2a65/easylistpolish/easylistpolish_specific_hide.txt#L2075

**Comment by adblock-filters** [comment]
Fixed in 7010e1c, thanks for spotting the problem and submitting issue!
