### ISSUE TITLE
www.liveads.pl

### ISSUE THREAD

**Issue by MajkiIT** [easylistpolish/easylistpolish#366]
blokuje filtr z `Easylist /liveads.`

**Comment by easylistpolish** [comment]
Hey, dzięki wielkie za info! Zgłosiłem to do EL, Może dodadzą wyjątek. Tak czy siak póki co dodałem filtr
https://github.com/easylistpolish/easylistpolish/commit/abef80ac292f79aba4f7dfcacfea6c1aad62880f

**Comment by MajkiIT** [comment]
@easylistpolish dzięki

**Comment by KrzysztofPPC** [comment]
Cześć, dzięki za zainteresowanie tematem. Niestety na chwilę obecną moja strona dalej wygląda jakby niewczytywał się szablon.

**Comment by easylistpolish** [comment]
Bardzo dziwne. Ten filtr działał jako dodany ręcznie, ale nie jak był na liście. Zmieniłem opcję i teraz jest ok
https://github.com/easylistpolish/easylistpolish/commit/469bcc51f649ad3e8f20d6b4308f54fb94997330
