### ISSUE TITLE
polskicaravaning.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#43]
bug - missing image:

![ss_374](https://user-images.githubusercontent.com/43844449/50447348-c9be4380-091a-11e9-9708-ef3761579757.png)

after disabling EasyList Polish
![ss_375](https://user-images.githubusercontent.com/43844449/50447354-d6429c00-091a-11e9-9cc7-dd4ace5a09ad.png)

**Comment by easylistpolish** [comment]
Can't reproduce, added:
polskicaravaning.pl##.baner
