### ISSUE TITLE
staleo.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#44]
from https://github.com/MajkiIT/polish-ads-filter/issues/10826

![ss380](https://user-images.githubusercontent.com/43844449/50607487-b0dd0180-0ec9-11e9-9f1c-7dde673b8c27.png)
![ss381](https://user-images.githubusercontent.com/43844449/50607488-b0dd0180-0ec9-11e9-840b-d8c71f314d6f.png)
![ss382](https://user-images.githubusercontent.com/43844449/50607489-b0dd0180-0ec9-11e9-8d53-651cac52560f.png)
![ss383](https://user-images.githubusercontent.com/43844449/50607491-b1759800-0ec9-11e9-898f-fbbdf5ad2c64.png)

**Comment by easylistpolish** [comment]
Added:
^banery^$domain=staleo.pl
staleo.pl##.silver.section-title
staleo.pl##.silver.section-title + aside
||staleo.pl^*^587c9a614cd75_
||staleo.pl^*^587c74fe36f77_
||staleo.pl^*^58ad3a2c4bf73_
