### ISSUE TITLE
megawypas.com

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#463]
EasyList Polish blokuje skrypt-pułapkę, co skutkuje anty-adblockiem:

<details not-open>
<summary>zrzut ekranu 1</summary>

![4](https://user-images.githubusercontent.com/43844449/79006414-654be580-7b59-11ea-929d-737aa80b7933.gif)

![1](https://user-images.githubusercontent.com/43844449/79006426-6b41c680-7b59-11ea-9413-c01061cef797.gif)

</details>

Rozwiązanie to albo dopuścić skrypt-pułapkę, albo zablokować skrypt anty-adblockowy:

<details not-open>
<summary>zrzut ekranu 2</summary>

![5](https://user-images.githubusercontent.com/43844449/79006545-afcd6200-7b59-11ea-8e61-4062950ab39b.gif)

![7](https://user-images.githubusercontent.com/43844449/79006785-308c5e00-7b5a-11ea-8749-4d44d14b0313.gif)

</details>

Dla ciekawiskich: nierozwijany już Fanboy Polish blokuje z kolei inny skrypt-pułapkę, co również skutkuje anty-adblockiem:

<details not-open>
<summary>zrzut ekranu 3</summary>

![8](https://user-images.githubusercontent.com/43844449/79007130-d50ea000-7b5a-11ea-8942-344a23d3e421.gif)

</details>

**Comment by easylistpolish** [comment]
Hej,
Dzięki za sugestię, ale nigdy nie podejmuję żadnych kroków, żeby omijać anty-adblock'i.
1. Uważam, że strona ma pełne prawo używać tego typu rozwiązań. Jeżeli mówią, że nie chcą użytkowników z adblockiem lub wręcz ich blockują, to ja nie powinienem blokować im tej możliwości, ani nie powinienem chować przed użytkownikiem tej informacji/blokady. 
2. Jest to zwyczajnie nielegalne

**Comment by kulfoon** [comment]
>  żeby omijać anty-adblock'i.

To mi się najwidoczniej coś pochrzaniło w takim razie, bo wydawało mi się, że zgłaszam błąd na liście, którego skutkiem ubocznym jest anty-adblock, a nie że zgłaszam samego anty-adblocka do rozbrojenia, który uwziął się na filtr, tzn. chodzi o to, co bylo pierwsze "kura czy jajko", jeśli najpierw był stworzony anty-adblock na stronie aktywujący się na filtr `/adserver.`, a dopiero potem dodany na EasyList Polish filtr `/adserver.` to tak jakby EasyList Polish dodało błędny filtr / zapomniało wykluczyć stronę/domenę z filtra i wpadło na anty-adblocka, który był już na stronie, ale mogło być odwrotnie - najpierw mógł zostać dodany filtr `/adserver.`  na EasyList Polish, a dopiero potem na stronie zrobili pułapkę pod ten filtr, wtedy faktycznie moje zgłoszenie byłoby omijaniem anty-adblocka, i tak chyba jest, że najpierw był dodany filtr do EasyList Polish, a dopiero potem oni zrobili pułapkę na filtr, bo ten filtr `/adserver.` jest tylko na EasyList Polish (no i na Fanboy's polish jest podobny) i nie ma go na innych listach więc żadne inne listy nie wpadają na tę pułapkę, więc gdyby mieli wczesniej zrobić pułapkę na ten filtr zanim został on dodany na EasyList Polish to nie miałoby to sensu bo nie było innej listy która by na tę pułapkę wpadła, więc chyba zrobili specjalnie pułapkę pod EasyList Polish, już po tym jak ten filtr został dodany do EasyList Polish, a mi się pochrzaniło, że było odwrotnie i potraktowałem to jako błąd w EasyList Polish.

**Comment by easylistpolish** [comment]
Hej
Na luzie. Po prostu moim zdaniem jeżeli oni wykrywają "generic" filtr, żeby sprawdzić, czy ktoś używa adblocka a ja bym dodał wyjątek, żeby to ominąć to dla mnie to jest to samo co jakbym dodał filtr żeby go zablokować

**Comment by kulfoon** [comment]
Ale jja estem całkowicie na luzie i o tym co napisałeś wiem i zgadzam się z tym, a ty doszukałeś się drugiego kontekstu/dna w mojej wypowiedzi, że niby mam jakiś żal / pretensje, otóż nie mam, chodziło mi tylko o to, co napisałem i o nic więcej, po prostu mi się coś pochrzaniło.

**Comment by easylistpolish** [comment]
Hej
Nie, nie szukam drugiego kontekstu, raczej bym zgadywał, że Twoja poprzednia wypowiedź jest poszukiwaniem jakichś ukrytych zamiarów.
Zacząłęm poprzednią wiadomość "Na luzie" i dopowiedziałem to czego nie było w mojej jeszcze poprzedniej wypowiedzi.

**Comment by kulfoon** [comment]
Acha, ok, ale ja również nie poszukiwałem ukrytych zamiarów, bo po prostu  "na luzie" to dla mnie zabrzmiało jakbyś chciał mnie uspokoić bo niby mam jakieś żale/pretensje, więc twoja wypowiedź była niejednoznaczna, i ja akurat odebrałem to drugie znaczenie, a o tym pierwszym nawet nie pomyślałem, a ty z kolei nie pomyślałeś o tym drugim, więc kogo wina, twoja, moja czy po środku? Nie wiem, więc niech zostanie po środku, to coś jak pytanie: co było pierwsza jajo czy kura. Hehe no zabawna sytuacja, Pozdro.
