### ISSUE TITLE
automobilista.com.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#47]
from https://github.com/MajkiIT/polish-ads-filter/issues/10820

1
![ss384](https://user-images.githubusercontent.com/43844449/50607662-41b3dd00-0eca-11e9-84a7-1ec568f350d7.png)

2
![ss385](https://user-images.githubusercontent.com/43844449/50607663-41b3dd00-0eca-11e9-82a8-d76e99f3b4f0.png)

**Comment by easylistpolish** [comment]
Added:
||automobilista.com.pl^*^2018/11/klas.
automobilista.com.pl##.adblock
automobilista.com.pl##.adblock + a
