### ISSUE TITLE
dziennikwschodni.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#5]
### Adblock detected  with EasyList:

- `###.ad-holder` [](https://github.com/AdguardTeam/AdguardFilters/issues/23446)

- `###.adholder`

- `?ads=$domain=~booking.loganair.co.uk`

### Screenshot:

> ![image](https://user-images.githubusercontent.com/35370833/46532200-2cfe8380-c8a0-11e8-97d9-bf1d604d6aff.png) |
> --- |

### Fix exceptions for EasyList filter:

<ul><li>
<pre><code>dziennikwschodni.pl<b>#@#</b>.ad-holder
dziennikwschodni.pl<b>#@#</b>.adholder
</code></pre>
</li><li>
<pre><code><b>@@</b>?ads=$<b>image</b>,<b>~third-party</b>,domain=dziennikwschodni.pl
</code></pre>
</li></ul>

**Comment by easylistpolish** [comment]
Hey krystian3w,
thanks for reporting this. Anyway Easylists are not fighting with anti-adblock issues. You can report this to Adblock Warning Removal List:
"Please report any unblocked obtrusive anti adblock messages or problems in the forums (https://forums.lanik.us/) or via e-mail (easylist.subscription+anti@gmail.com)."
Greetings
