### ISSUE TITLE
lacha.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#52]
###### domain:

`http://www.lacha.pl/`

###### filters: 

```
lacha.pl##.reklama_under
lacha.pl###divExoLayerWrapper
```

###### screen:

<details> <summary> screenshoot  (<b>nudity</b> :warning:) </summary>

![obraz](https://user-images.githubusercontent.com/35370833/51803953-2df65f00-225b-11e9-872f-aea1f5f605da.png) |
--- |

**Comment by easylistpolish** [comment]
Added
##.reklama_under
lacha.pl###divExoLayerWrapper
