### ISSUE TITLE
mojaolesnica.pl (2)

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#53]
Reopening https://github.com/easylistpolish/easylistpolish/issues/34 because now "reclama" texts appear all over the page, thus perhaps now it's worth to block it:

Main page:

1
![ss459](https://user-images.githubusercontent.com/43844449/51805070-45d4df80-2269-11e9-9f99-7a7ed6cabbac.png) 

2
![ss460](https://user-images.githubusercontent.com/43844449/51805071-466d7600-2269-11e9-8212-b27d34fdc05c.png)

3
![ss461](https://user-images.githubusercontent.com/43844449/51805072-466d7600-2269-11e9-9f8f-6e2dd4942e31.png)

4
![ss462](https://user-images.githubusercontent.com/43844449/51805073-466d7600-2269-11e9-9b84-f8dcf598afc7.png)

5
![ss463](https://user-images.githubusercontent.com/43844449/51805074-47060c80-2269-11e9-9e7e-9dca262b01a8.png)

6
![ss464](https://user-images.githubusercontent.com/43844449/51805076-479ea300-2269-11e9-8f8b-0380c9135c40.png)

7
![ss465](https://user-images.githubusercontent.com/43844449/51805077-479ea300-2269-11e9-80d0-3ceb2b35c857.png)

Article subpage for. ex. https://mojaolesnica.pl/27336,szeryf-z-piszkawy-pytanie.php:

1
![ss468](https://user-images.githubusercontent.com/43844449/51805104-a532ef80-2269-11e9-9443-2a27a78ac1b0.png)

2
![ss466](https://user-images.githubusercontent.com/43844449/51805100-a49a5900-2269-11e9-8c10-087e164f0caa.png)

3
![ss467](https://user-images.githubusercontent.com/43844449/51805103-a532ef80-2269-11e9-91a1-38ce368b6210.png)

**Comment by easylistpolish** [comment]
Added
mojaolesnica.pl##div[style^="margin-left: auto; overflow: hidden;width:"]
