### ISSUE TITLE
radioznin.fm

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#55]
Not fixed in: https://github.com/MajkiIT/polish-ads-filter/issues/11658
 "reclama" texts appear all over the page:

Main page:

1 top-left
![ss469](https://user-images.githubusercontent.com/43844449/51805203-deb82a80-226a-11e9-9f70-69fdd52e69e8.png)

2 right 
![ss470](https://user-images.githubusercontent.com/43844449/51805204-deb82a80-226a-11e9-9c53-aadc319075d3.png)

3 right
![ss471](https://user-images.githubusercontent.com/43844449/51805205-deb82a80-226a-11e9-93b2-de335f2110e4.png)

4 bottom-left
![ss472](https://user-images.githubusercontent.com/43844449/51805206-deb82a80-226a-11e9-9916-bc4cfa753dde.png)

Article subpage:

1 top-left
![ss473](https://user-images.githubusercontent.com/43844449/51805224-0f985f80-226b-11e9-8dab-6c8df24714e9.png)

2 right:
![ss474](https://user-images.githubusercontent.com/43844449/51805225-1626d700-226b-11e9-8755-57c0b266d969.png)

**Comment by easylistpolish** [comment]
A: radioznin.fm##.bannergroup
