### ISSUE TITLE
damitv.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#57]
After banners have been fixed in https://github.com/MajkiIT/polish-ads-filter/issues/11667, now "reclama" texts appear all over the page in article subpages:

1 left
![ss475](https://user-images.githubusercontent.com/43844449/51805260-b8df5580-226b-11e9-9bd4-3e7f217aa2be.png)

2 right
![ss476](https://user-images.githubusercontent.com/43844449/51805264-bb41af80-226b-11e9-8e35-8badd5d8b553.png)

3 left
![ss477](https://user-images.githubusercontent.com/43844449/51805265-bbda4600-226b-11e9-943a-9b070eadfbf7.png)

**Comment by easylistpolish** [comment]
page inactive
