### ISSUE TITLE
elektroda.pl - zablokowane obrazki

### ISSUE THREAD

**Issue by gulson-elektroda** [easylistpolish/easylistpolish#589]
Witajcie,

Wprowadzoną regułką:
elektroda.pl##a[target="_blank"]:not([href*="elektroda.pl"]) > img[alt]
w commicie:
https://github.com/easylistpolish/easylistpolish/commit/29ee40f1908b70aa267194f6870235646f1ae044#
zablokowaliście WSZYSTKIE obrazki, które linkują poza domenę elektroda.pl, tym samym uszkadzając tysiące postów użytkowników, przykład postu:
https://www.elektroda.pl/rtvforum/viewtopic.php?p=18226797#18226797
gdzie użytkownik linkuje obrazek do pagespeed.

**Comment by adblock-filters** [comment]
@easylistpolish #593

**Comment by easylistpolish** [comment]
Hey, filter usunięty
