### ISSUE TITLE
tv.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#6]
### Anti-adblock with EasyPrivacy:

`/dotn?*&pg=http`

[](https://github.com/MajkiIT/polish-ads-filter/issues/9621)

### Fix for EasyPrivacy:

<pre><code>@@||tv.wp.pl/do/*<b>/dotn?sw=</b>$image,~third-party,domain=tv.wp.pl
</code></pre>

**Comment by gargaamel** [comment]
The fix doesn't work with EasyList Polish, coz there is even no `/dotn?*&pg=http` request with EasyList Polish enabled, so there is nothing to whitelist with this exception filter.

**Comment by krystian3w** [comment]
probably already network approvals have disappeared about 24 hours have already popped up again "pop-up".

I did not check to what extent the project itself generates an anti-adblock message.

**Comment by krystian3w** [comment]
In addition, it may not be repaired, so that it is not that psuty is anti-adblock wall - that according to Eyeo GMBH, you can not move without lawsuits.

**Comment by krystian3w** [comment]
> Hey krystian3w,
> thanks for reporting this. Anyway Easylists are not fighting with anti-adblock issues. You can report this i.e. to Adblock Warning Removal List:
> "Please report any unblocked obtrusive anti adblock messages or problems in the forums (https://forums.lanik.us/) or via e-mail ([easylist.subscription+anti@gmail.com](mailto:easylist.subscription+anti@gmail.com))."
> Greetings
