### ISSUE TITLE
elektroda.pl - reklama i sponsorowane

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#673]
### 1. Wysypało na głównej reklamę kwadratową po prawej stronie jak w poprzednim zgłoszeniu https://github.com/easylistpolish/easylistpolish/issues/429#issue-595763684 : 

![](https://user-images.githubusercontent.com/43844449/78656949-661a1880-78c8-11ea-8010-55eec3e05e56.gif)

### 2. Wysypało sponsorowane (żółte) na forum: https://www.elektroda.pl/rtvforum/topic3508518.html

![capture_002_21-05-2020_22-43-17](https://user-images.githubusercontent.com/43844449/82605504-4f98f980-9bb6-11ea-9a24-a63f23947734.gif)

![capture_003_21-05-2020_22-43-22](https://user-images.githubusercontent.com/43844449/82605486-4c057280-9bb6-11ea-9281-5b33ae44a914.gif)

**Comment by TrollZbozowy** [comment]
Dzięki za za zgłoszenie, wysłałem propozycję 'naprawy', nie jestem do końca pewny co z linkiem 3 z trzeciego screenu.

**Comment by adblock-filters** [comment]
tutaj raczej większość linków sponsorowanych z trzeciego screenu przekierowuje do artykułów na elektrodzie, więc nie możemy takich blokować @kulfoon  ; )

**Comment by kulfoon** [comment]
OK.

**Comment by easylistpolish** [comment]
Heyo, pchnąłem pull requesta i dodałem dodatkowy filtr.
Co do 3ciego zgłoszenia, powiedziałbym, że jest to na granicy, ale ja też bym nie blokował. Mały, nie denerwujący link do artkułu, częściowo związany z treścią strony, na samym dole, wyraźnie zaznaczony jako sponsorowany.
https://github.com/easylistpolish/easylistpolish/commit/d2718de1a66a2ea032352dfc302f8e62def41c32
https://github.com/easylistpolish/easylistpolish/commit/78ac97b47509f94e5a4216e27e073cbea6da381c
