### ISSUE TITLE
bestofwhisky.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#68]
"Reclama text x 2:

1 Top:
![ss489](https://user-images.githubusercontent.com/43844449/51805425-55562780-226d-11e9-9322-3f3646884024.png)

2 Bottom:
![ss490](https://user-images.githubusercontent.com/43844449/51805427-57b88180-226d-11e9-86c5-fb2a0491c8d6.png)

**Comment by easylistpolish** [comment]
Added:
bestofwhisky.pl##.contetn-left-ad-top
