### ISSUE TITLE
daiglob.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#70]
"Reclama" text x 2:

1 middle:
![ss492](https://user-images.githubusercontent.com/43844449/51805440-8df60100-226d-11e9-9331-5b5341a91191.png)

2 bottom:
![ss493](https://user-images.githubusercontent.com/43844449/51805441-8fbfc480-226d-11e9-8ad5-b3bb287d8d55.png)

**Comment by easylistpolish** [comment]
Not worth to block it
