### ISSUE TITLE
wiedzanaplus.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#74]
"Reclama text x 3:

1 top-left:
![ss497](https://user-images.githubusercontent.com/43844449/51805474-08bf1c00-226e-11e9-90d2-14d26e3bfa0f.png)

2 right:
![ss498](https://user-images.githubusercontent.com/43844449/51805478-0bba0c80-226e-11e9-8d7d-6b0223598d07.png)

3 bottom-left:
![ss499](https://user-images.githubusercontent.com/43844449/51805480-0eb4fd00-226e-11e9-9afe-7b40301d8101.png)

**Comment by easylistpolish** [comment]
Not worth to add it
