### ISSUE TITLE
popularcoffee.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#77]
"Reclama text x 2:

1 right:
![ss502](https://user-images.githubusercontent.com/43844449/51805513-73705780-226e-11e9-96f2-335be927af70.png)

2 bottom:
![ss503](https://user-images.githubusercontent.com/43844449/51805514-753a1b00-226e-11e9-9c2d-3a5b054ea05d.png)

**Comment by easylistpolish** [comment]
A: popularcoffee.pl##.stf-adsense
