### ISSUE TITLE
ostrowiecnews.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#80]
"Reclama" text top-left:

![ss507](https://user-images.githubusercontent.com/43844449/51805544-f5f91700-226e-11e9-8b53-d4b0e874ebea.png)

**Comment by easylistpolish** [comment]
Added
ostrowiecnews.pl##p[style='margin-left:120px;"']
ostrowiecnews.pl##p[style='margin-left:120px;"'] + center
