### ISSUE TITLE
styluva.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#81]
"Reclama" text x 2:

1 right:
![ss508](https://user-images.githubusercontent.com/43844449/51805551-11642200-226f-11e9-88e3-2883a3630da7.png)

2 right:
![ss509](https://user-images.githubusercontent.com/43844449/51805553-13c67c00-226f-11e9-91dc-ff315ca16953.png)

**Comment by easylistpolish** [comment]
Not worth to add it
