### ISSUE TITLE
elektroda.pl - zablokowane obrazki na forum #2

### ISSUE THREAD

**Issue by gulson-elektroda** [easylistpolish/easylistpolish#830]
Witajcie,
Wprowadzoną regułką:
elektroda.pl##a[target="_blank"]:not([href*="elektroda.pl"]) > img[alt]
w commicie:
https://github.com/easylistpolish/easylistpolish/commit/b34d7a3b1607cd7fb91ab08d9f94449ba46ab532
zablokowaliście WSZYSTKIE obrazki, które linkują poza domenę elektroda.pl, tym samym uszkadzając tysiące postów użytkowników, przykład postu:
https://www.elektroda.pl/rtvforum/viewtopic.php?p=18226797#18226797
gdzie użytkownik linkuje obrazek do pagespeed.

**Comment by easylistpolish** [comment]
Przepraszam, przeoczyłem przy rozwiązywaniu merge conflict'u, że wcześniej usunięty filtr, chce się dodać.
Usunięte ponownie
https://github.com/easylistpolish/easylistpolish/commit/6aa60bbddb83761a1d39e29f223e2dc5edc8fcc9
