### ISSUE TITLE
przecinek w domain=

### ISSUE THREAD

**Issue by bug-rules** [easylistpolish/easylistpolish#831]
https://github.com/easylistpolish/easylistpolish/blob/663cad97f64a4da185a755ebe7a02727595d41ef/easylistpolish/easylistpolish_specific_block.txt#L72

Powinno być: `|`

---

Efekt, że pewnie filtr wcale nie działa lub tylko na pierwszej domenie.

**Comment by TrollZbozowy** [comment]
hey, dzieki za zgloszenie

fix
https://github.com/easylistpolish/easylistpolish/pull/832
