### ISSUE TITLE
chcemybycrodzicami.pl

### ISSUE THREAD

**Issue by gargul2** [easylistpolish/easylistpolish#833]
Błąd - filtr `chcemybycrodzicami.pl##.the-a` coś usuwa ale nie docina tła:

### 1 z filterm
![capture_458_30-06-2020_10-22-43](https://user-images.githubusercontent.com/63287518/86102865-591e5700-babc-11ea-87e2-c2655c3a6fe7.gif)

### 2 bez filtra
![capture_457_30-06-2020_10-22-00](https://user-images.githubusercontent.com/63287518/86102888-60456500-babc-11ea-85d1-a0c9c5b6f2e2.gif)

### 3 po wejściu na stronę
![capture_459_30-06-2020_10-22-50](https://user-images.githubusercontent.com/63287518/86102955-75ba8f00-babc-11ea-812d-b6ff7204f36e.gif)

**Comment by adblock-filters** [comment]
Hej, dzięki za zgłoszenie. ; )
Zmieniłem `chcemybycrodzicami.pl##.the-a` na:
* `chcemybycrodzicami.pl##.row > the-a`
* `^baner_$domain=chcemybycrodzicami.pl`

Co prawda popup musi zostać gdyż to autopromocja, ale reszta jest naprawiona.
