### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by gargul2** [easylistpolish/easylistpolish#835]
https://github.com/MajkiIT/polish-ads-filter/issues/16803

**Comment by adblock-filters** [comment]
dzięki za zgłoszenie, dodałem
`elektroda.pl##.menuBarAd:not([href*="elektroda.pl/"])`
`elektroda.pl###news a[href^="https://jlcpcb.com/"][rel^="nofollow"]`
#841 
blokuje tylko kilka na głównej, ale dodam filtr do **anit-cv** żeby poblokować te zmieniające się klasy  :smirk:
