### ISSUE TITLE
csbydgoszcz.pl

### ISSUE THREAD

**Issue by krystian3w** [easylistpolish/easylistpolish#844]
### URL:

`https://www.csbydgoszcz.pl/`

### What happend:

https://github.com/easylistpolish/easylistpolish/blob/a5e40086fdd9723763987862da8d76668a4a7d10/easylistpolish/easylistpolish_general_block.txt#L4

break page: https://github.com/AdguardTeam/AdguardFilters/issues/59659 / https://forums.lanik.us/viewtopic.php?p=155783#p155783

hides pictures that are not real advertising (also that images are not self-promotions either).

### Notes:

Need exception like as `selgros24.pl`:
https://github.com/easylistpolish/easylistpolish/blob/a68bf1db635c285fd476dc09fa3f71ff223318e0/easylistpolish/easylistpolish_whitelist.txt#L11

**Comment by adblock-filters** [comment]
:+1:
