### ISSUE TITLE
infosiedlce.pl + golub-cgd.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#85]
Ads, was reported 2 times:
https://github.com/MajkiIT/polish-ads-filter/issues/11643
https://github.com/MajkiIT/polish-ads-filter/issues/11729
but the admin didn't fix them:

infosiedlce.pl
![51708466-429ce200-2024-11e9-830e-dce6fe1f226e](https://user-images.githubusercontent.com/43844449/51894514-3a3c0280-23a8-11e9-95a7-f3d395e34815.png)

golub-cgd.pl
![51708640-acb58700-2024-11e9-81ca-dabca74ac399](https://user-images.githubusercontent.com/43844449/51894521-3d36f300-23a8-11e9-92cb-e99e09da2b01.png)

**Comment by easylistpolish** [comment]
Page uses anti-adblock. I won't block ads on these pages

**Comment by krystian3w** [comment]
YouTube also have, so delete filters from "English" EasyList? https://github.com/easylist/easylist/

**Comment by easylistpolish** [comment]
AFAIK, Youtube doesn't use anti-adblock at all
