### ISSUE TITLE
ecoenergia.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#86]
2 x Reklama text

![ss536](https://user-images.githubusercontent.com/43844449/52900351-1cb6c780-31f5-11e9-9d09-a6ed7504a617.png)

left
![ss537](https://user-images.githubusercontent.com/43844449/52900346-11fc3280-31f5-11e9-9d2f-4826f9de8e3f.png)

right
![ss538](https://user-images.githubusercontent.com/43844449/52900347-1294c900-31f5-11e9-8220-1e5558baa6c1.png)

**Comment by easylistpolish** [comment]
Page is inactive since 2015
