### ISSUE TITLE
elpcmaniak.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#89]
2 x "reklama" text

1 right side:
![ss575](https://user-images.githubusercontent.com/43844449/52916109-f61f8c00-32db-11e9-8606-8ea96c6bb2e1.png)

2 bottom-left:
![ss576](https://user-images.githubusercontent.com/43844449/52916113-fddf3080-32db-11e9-8634-7d22d799acf1.png)

**Comment by easylistpolish** [comment]
Not worth to add it
