### ISSUE TITLE
elka.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#9]
As per https://github.com/MajkiIT/polish-ads-filter/issues/9152
Ads remains / text / placeholders "reklama" :

### `http://elka.pl`
![ss015](https://user-images.githubusercontent.com/43844449/48663899-0767bb00-ea97-11e8-95f6-667f5af975b6.png)

### `http://elka.pl/content/view/90791/80/`
![ss016](https://user-images.githubusercontent.com/43844449/48663903-10588c80-ea97-11e8-8981-a09283b16b29.png)

**Comment by easylistpolish** [comment]
Right sign hided. The rest needs extended filters
