### ISSUE TITLE
galopuje.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#91]
2 x "Reklama" text on the right:

1
![ss578](https://user-images.githubusercontent.com/43844449/53012942-af997100-3444-11e9-8e69-bbbe1989a188.png)

2
![ss577](https://user-images.githubusercontent.com/43844449/53012940-af00da80-3444-11e9-8fb3-797987a77a1f.png)

**Comment by easylistpolish** [comment]
Not worth to add
