### ISSUE TITLE
senior.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#96]
2 x "Reklama" text:

1
![ss582](https://user-images.githubusercontent.com/43844449/53358501-dcf88a00-3930-11e9-85e9-b03bd3dd075c.png)

2
![ss583](https://user-images.githubusercontent.com/43844449/53358502-dd912080-3930-11e9-9cc3-2635c10e283a.png)

**Comment by easylistpolish** [comment]
Not worth to add
