### ISSUE TITLE
pikio.pl

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#98]
3 x "Reklama" text:

1
![ss585](https://user-images.githubusercontent.com/43844449/53358590-0d402880-3931-11e9-9873-9ef2bee0d82b.png)

2
![ss586](https://user-images.githubusercontent.com/43844449/53358592-0d402880-3931-11e9-873a-0447e7bf3cab.png)

3
![ss587](https://user-images.githubusercontent.com/43844449/53358593-0d402880-3931-11e9-809e-c05672fe0574.png)

**Comment by easylistpolish** [comment]
Can't reproduce
